web_app/web_app/models.py
from web_app import db

class Alloys(db.Model):

    __tabelname__='alloys'

    id=db.Column(db.Integer,primary_key=True)
    #sr_id=db.Column(db.Integer)
    c=db.Column(db.Numeric(2,4),nullable=False,index=True)
    si=db.Column(db.Numeric(2,4),nullable=False,index=True)
    mn=db.Column(db.Numeric(2,4),nullable=False,index=True)
    p=db.Column(db.Numeric(2,4),nullable=False,index=True)
    s=db.Column(db.Numeric(2,4),nullable=False,index=True)
    ni=db.Column(db.Numeric(2,4),nullable=False,index=True)
    cr=db.Column(db.Numeric(2,4),nullable=False,index=True)
    mo=db.Column(db.Numeric(2,4),nullable=False,index=True)
    cu=db.Column(db.Numeric(2,4),nullable=False,index=True)
    v=db.Column(db.Numeric(2,4),nullable=False,index=True)
    al=db.Column(db.Numeric(2,4),nullable=False,index=True)
    n=db.Column(db.Numeric(2,4),nullable=False,index=True)
    nt=db.Column(db.Numeric(2,4),nullable=False,index=True)
    temp=db.Column(db.Integer,nullable=False,index=True)
    tensile=db.Column(db.Numeric(5,4),nullable=False,index=True)
    yield_=db.Column(db.Numeric(5,4),nullable=False,index=True)
    elongation=db.Column(db.Numeric(5,4),nullable=False,index=True)
    reduction=db.Column(db.Numeric(5,4),nullable=False,index=True)

    def __init__(self,c,si,mn,p,s,ni,cr,mo,cu,v,al,n,nt,temp,tensile,yield_,elongation,reduction):
        self.c,self.si,self.mn,self.p,self.s,self.ni,self.cr,self.mo,self.cu,self.v,self.al,self.n,self.nt,self.temp,self.tensile,self.yield_,self.elongation,self.reduction=c,si,mn,p,s,ni,cr,mo,cu,v,al,n,nt,temp,tensile,yield_,elongation,reduction

    # def __repr__(self):
    #     return f"Carbon:{self.c},Silicon:{self.si},Manganese:{self.mn},Phosphorus:{self.p},Sulphur:{self.s},Nickel:{self.ni},Chromium:{self.cr},Molybdenum:{self.mo},Copper:{self.cu},Vanadium:{self.v},Aluminium:{self.al},Nitrogen:{self.n},Nb+Ta:{self.nt},Temperature:{self.temp},Tensile Strength:{self.tensile}"

web_app/web_app/__init__.py
from flask import Flask
import os
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

#----------------APP------------------#
app=Flask(__name__)
app.config['SECRET_KEY']='mysecretkey'
#-------------------------------------#

#---------------DATABASE--------------#
basedir=os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///'+os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False

db=SQLAlchemy(app)
Migrate(app,db)
#-------------------------------------#


#------------BLUEPRINTS-------------#
from web_app.home.views import home
app.register_blueprint(home)

from web_app.lab.views import lab
app.register_blueprint(lab)

from web_app.logs.views import logs
app.register_blueprint(logs)

from web_app.error_pages.handler import error_pages
app.register_blueprint(error_pages)
#-----------------------------------#

web_app/web_app/home/views.py
from flask import render_template,Blueprint

home=Blueprint('home',__name__)

@home.route('/',methods=["GET","POST"])
def index():
    return render_template('index.html')

web_app/web_app/lab/views.py
from flask import render_template,request,redirect,url_for,Blueprint
from web_app.lab.test_model import MechanicalProperties
from web_app import db
from web_app.models import Alloys

lab=Blueprint('lab',__name__)


@lab.route('/lab',methods=["GET","POST"])
def lab_():

    if request.method=="POST":
        _c,_si,_mn,_p,_s,_ni,_cr,_mo,_cu,_v,_al,_n,_nt,_temp=request.form.get("_carbon"),request.form.get("_silicon"),request.form.get("_manganese"),request.form.get("_phosphorus"),request.form.get("_sulphur"),request.form.get("_nickel"),request.form.get("_chromium"),request.form.get("_molybdenum"),request.form.get("_copper"),request.form.get("_vanadium"),request.form.get("_aluminium"),request.form.get("_nitrogen"),request.form.get("_nbta"),request.form.get("_temp")

        elems=[_c,_si,_mn,_p,_s,_ni,_cr,_mo,_cu,_v,_al,_n,_nt,_temp]
        if _si==_p==_s==_ni==_cr==_mo==_cu==_v==_al==_n==_nt==_temp or (_si==_p==_s==_ni==_cr==_mo==_cu==_v==_al==_n==_nt):
            error="All values can not be same!"
            return render_template('lab.html',elm1=_c,elm2=_si,elm3=_mn,elm4=_p,elm5=_s,elm6=_ni,elm7=_cr,elm8=_mo,elm9=_cu,elm10=_v,elm11=_al,elm12=_n,elm13=_nt,elm14=_temp,error=error)
        
        elif elems.count('0')>6:
            error="Too many values are null!"
            return render_template('lab.html',elm1=_c,elm2=_si,elm3=_mn,elm4=_p,elm5=_s,elm6=_ni,elm7=_cr,elm8=_mo,elm9=_cu,elm10=_v,elm11=_al,elm12=_n,elm13=_nt,elm14=_temp,error=error)

        mp=MechanicalProperties(elems)
        pred_tensile=mp.predict_tensile_strength()
        pred_yield=mp.predict_yield_strength()
        pred_elong=mp.predict_elongation()
        pred_ria=mp.predict_reduction_in_area()
        
        comps=Alloys(c=_c,si=_si,mn=_mn,p=_p,s=_s,ni=_ni,cr=_cr,mo=_mo,cu=_cu,v=_v,al=_al,n=_n,nt=_nt,temp=_temp,tensile=pred_tensile,yield_=pred_yield,elongation=pred_elong,reduction=pred_ria)
        db.session.add(comps)
        db.session.commit()
        
        return render_template('lab.html',ria_val=pred_ria,elong_val=pred_elong,yield_val=pred_yield,tensile_val=pred_tensile,elm1=_c,elm2=_si,elm3=_mn,elm4=_p,elm5=_s,elm6=_ni,elm7=_cr,elm8=_mo,elm9=_cu,elm10=_v,elm11=_al,elm12=_n,elm13=_nt,elm14=_temp)

    return render_template('lab.html')

web_app/web_app/logs/views.py
from flask import render_template,request,redirect,url_for,Blueprint
from web_app import db
from web_app.models import Alloys

logs=Blueprint('logs',__name__)

@logs.route('/logs',methods=["GET","POST"])
def log():
    alloys_=Alloys.query.all()

    if request.method == 'POST':
        if request.form.get('Continue')=='Continue':
            db.session.query(Alloys).delete()
            db.session.commit()
        return redirect(url_for("logs.log",alloys_=alloys_))

    return render_template('log.html',alloys_=alloys_)

# @history.route('/history',methods=["GET","POST"])
# def delete_row(pid):
#     num=0
#     if request.method == 'POST':
#         if request.form.get('Delete') == 'Delete':
#             print('now in here')
#             pid=pid
#             del_id=request.form.get("id")
#             return redirect(url_for('history.html',alloys_=alloys_,num=pid))

#         else:
#             return redirect(url_for('history.html',alloys_=alloys_,num=pid))

# @history.route('/history',methods=["GET","POST"])
# def clear():
#     print('its in clear')
#     if request.method == 'POST':
#         if request.form.get('clear_num')==1:
#             db.session.query(Alloys).delete()
#             db.session.commit()
#             print('it worked!')
#             return redirect(url_for('history.hist'))

web_app/web_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <title>Welcome!</title><script src="http://code.jquery.com/jquery-1.11.1.js"></script><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="utf-8">
    <!--
    <link type="text/css" rel="stylesheet" href="css//style.css">
-->
    
    <style>
        /* Chrome, Safari, Edge, Opera */
        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
          -webkit-appearance: none;
          margin: 0;
        }
        
        /* Firefox */
        input[type=number] {
          -moz-appearance: textfield;
        }

        .css-serial {
          counter-reset: serial-number;  /* Set the serial number counter to 0 */
        }
  
        .css-serial td:first-child:before {
          counter-increment: serial-number;  /* Increment the serial number counter */
          content: counter(serial-number);  /* Display the counter */
        }
        
        .boxsize {
          height: 30px;
          width: 70px;
          margin-left: -60px
        }
        /*
        .mt-0 {
          margin-top: 0 !important;
        }
        */
        .paramsize {
          padding-top: 10px;
          height: 30px;
        }

        .fixeddiv {
          position: fixed;
        }

        .resetbuttonsize {
          position: fixed;
          height: 35px;
          width: 70px;
        }

        .clearbuttonsize {
          position: fixed;
          height: 35px;
          width: 80px;
        }

        .logbuttonsize {
          height: 35px;
          width: 70px;
        }

        .unitsize {
          height: 30px;
          width: 50px;
        }
        /*
        body {
          background-image: url('static\\1477277.jpg');
        }
        */
        body {
          background-color: #A6A6A6;
          padding-top: 70px;
        }

        .table-headers {
          background-color: #F2F2F2;
        }
        
        .lab-logo {
          margin-left: -70px;
          background-color: #A6A6A6;
          clip-path: circle();

        }

        .card-bg {
          background-color: #F2F2F2;
        }

        .modalbox {
          padding-top: 30px;
        }

        .navbar {
          background-color: #F2F2F2;
        }

    </style>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{url_for('home.index')}}">Home</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('lab.lab_')}}">Laboratory</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('logs.log')}}">Logs</a>
            </li>
            <!---------------------------->
            
            <!---------------------------->
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

web_app/web_app/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h2 style="font-family: 'Noto Serif', serif;">MachineLurgy</h2>
    <br>
    <div class="row">
        <div class="col-sm-6">
            <div class="card card-bg" style="width: 35em;">
                <div class="card-body">
                  <h5 class="card-title fw-bold" style="color:blue;">About</h5>
                  <hr>
                  <p class="card-text">
                      MachineLurgy is a web-based application that can predict the mechanical properties of low-alloy steel when provided with required compositons.
                      As currently there are no precise theoretical methods to predict mechanical properties of steels, all the methods available are backed by statistics 
                      and extensive physical testing of the materials.<br><br> Since testing each material with different composition is a highly tedious task (imagine the number 
                      of possibilities!), MachineLurgy helps practitioners to come up with a set of best low-alloy steels that possess required mechanical properties just by providing 
                      composition of the steel.
                  </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card card-bg" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title fw-bold" style="color:blue;">Features</h5>
                  <hr>
                  <p class="fw-bold">&#9758 User-friendly UI</p>
                  <p class="fw-bold">&#9758 Predicts properties such as<br> &emsp;&ensp; - Tensile Strength<br>&emsp;&ensp; - Yield Strength<br>&emsp;&ensp; - Elongation<br>&emsp;&ensp; - Reduction in Area</p>
                  <p class="fw-bold">&#9758 Keeps track of all<br> &emsp;&ensp; observations</p>
                </div>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}

web_app/web_app/templates/lab.html
{% extends "base.html"%}
{% block content %}

<div class="container">

        <form class="from-inline" role="form">
            <div class="row">
                <div class="col-sm-2"><h4 style="font-family: 'Noto Serif', serif;">Experiment</h4></div>
                <div class="col-sm-2"><img class="lab-logo" src="static//lab_logo.png" alt="" width="50" height="40"></div>
            </div>
        </form>
        
        <form class="from-inline" role="form">
                <label class="fw-bold" style="font-family: 'Noto Serif', serif;">Enter the weight percentage(%w) of each element below: </label>
                <a tabindex="0" class="button" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="<b>Note</b>" data-bs-content="In order to get the maximum accuracy, enter the value within the specified range for each element. <br /> <b>Hover over the input field to see the lower and upper limits.</b>" data-bs-html="true" style="border: none; background-color: #A6A6A6; color: black;">
                    <i class="bi bi-info-circle"></i>
                </a>
        </form>

    <form action="{{url_for('lab.lab_')}}" method="POST">
        <div class="unit">
            <div class="row mb-3">
                <label for="carbon" class="col-sm-2 col-form-label">Carbon(C)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" id="carbon" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" title="min: 0.025&#013;<br>max: 0.35" name="_carbon" value="{{elm1}}"  min="0.025" max="0.35" step=0.0001 required>
                </div>
                <label for="silicon" class="col-sm-2 col-form-label">Silicon(Si)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" id="silicon" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" title="min: 0&#013;<br>max: 0.55" name="_silicon" value="{{elm2}}"  min="0" max="0.55" step=0.0001 required>
                </div>
                <div class="col-sm-2" style="padding-left: 45px;">
                    <button type="submit" class="form-control btn btn-primary btn-sm clearbuttonsize" value="Submit">Compute</button>
                </div>
                <label for="tensile" class="col-sm-2 col-form-label">Tensile Strength</label>
                <div class="col-sm-2">
                    <div class="input-group">
                        <input type="number" class="form-control paramsize mt-1" id="tensile" value="{{tensile_val}}" step=0.0001 readonly style="text-align: center;">
                        <div class="input-group-text unitsize mt-1">MPa</div>                
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                <label for="manganese" class="col-sm-2 col-form-label">Manganese(Mn)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" id="manganese" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" title="min: 0.3&#013;<br>max: 1.8" name="_manganese" value="{{elm3}}"  min="0.3" max="1.8" step=0.0001 required>
                </div>
                <label for="phosphorus" class="col-sm-2 col-form-label">Phosphorus(P)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" id="phosphorus" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" title="min: 0&#013;<br>max: 0.05" name="_phosphorus" value="{{elm4}}"  min="0" max="0.05" step=0.0001 required>
                </div>
                <div class="col-sm-2" style="padding-left: 50px;">
                    <input type='button' class="form-control btn btn-secondary btn-sm resetbuttonsize" value='Reset' name='reset' onclick="return clearForm(this.form);">
                </div>
                <label for="yield" class="col-sm-2 col-form-label">Yield Strength</label>
                <div class="col-sm-2">
                    <div class="input-group">
                        <input type="number" class="form-control paramsize mt-1" id="yield" value="{{yield_val}}" step=0.0001 readonly style="text-align: center;">
                        <div class="input-group-text unitsize mt-1">MPa</div>                
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                <label for="sulphur" class="col-sm-2 col-form-label">Sulphur(S)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" id="sulphur" name="_sulphur" value="{{elm5}}" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" title="min: 0&#013;<br>max: 0.05" min="0" max="0.05" step=0.0001 required>
                </div>
                <label for="nickel" class="col-sm-2 col-form-label">Nickel(Ni)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" id="nickel" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" name="_nickel" value="{{elm6}}" title="min: 0&#013;<br>max: 0.6"  min="0" max="0.6" step=0.0001 required>
                </div>
                <label for="ria" class="col-sm-2 col-form-label"></label>
                <label for="elongation" class="col-sm-2 col-form-label">Elongation</label>
                <div class="col-sm-2">
                    <div class="input-group">
                        <input type="number" class="form-control paramsize mt-1" id="elongation" value="{{elong_val}}" step=0.01 readonly style="text-align: center;">
                        <div class="input-group-text unitsize mt-1">%</div>                
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                <label for="chromium" class="col-sm-2 col-form-label">Chromium(Cr)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" id="chromium" name="_chromium" value="{{elm7}}" title="min: 0&#013;<br>max: 1.45"  min="0" max="1.45" step=0.0001 required>
                </div>
                <label for="molybdenum" class="col-sm-2 col-form-label">Molybdenum(Mo)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" id="molybdenum" name="_molybdenum" value="{{elm8}}" title="min: 0&#013;<br>max: 1.35"  min="0" max="1.35" step=0.0001 required>
                </div>
                <label for="ria" class="col-sm-2 col-form-label"></label>
                <label for="ria" class="col-sm-2 col-form-label">Reduction In Area</label>
                <div class="col-sm-2">
                    <div class="input-group">
                        <input type="number" class="form-control paramsize mt-1" id="ria" value="{{ria_val}}" step=0.01 readonly style="text-align: center;">
                        <div class="input-group-text unitsize mt-1">%</div>                
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                <label for="copper" class="col-sm-2 col-form-label">Copper(Cu)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" id="copper" name="_copper" value="{{elm9}}" title="min: 0&#013;<br>max: 0.25" min="0" max="0.25" step=0.0001 required>
                </div>
                <label for="vanadium" class="col-sm-2 col-form-label">Vanadium(V)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" id="vanadium" name="_vanadium" value="{{elm10}}" title="min: 0&#013;<br>max: 0.3"  min="0" max="0.3" step=0.0001 required>
                </div>
            </div>
            <div class="row mb-3">
                <label for="aluminium" class="col-sm-2 col-form-label">Aluminium(Al)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" id="aluminium" name="_aluminium" value="{{elm11}}" title="min: 0&#013;<br>max: 0.05" min="0" max="0.05" step=0.0001 required>
                </div>
                <label for="nitrogen" class="col-sm-2 col-form-label">Nitrogen(N)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" id="nitrogen" name="_nitrogen" value="{{elm12}}" title="min: 0&#013;<br>max: 0.015"  min="0" max="0.015" step=0.0001 required>
                </div>
            </div>
            <div class="row mb-3">
                <label for="nbta" class="col-sm-2 col-form-label">Niobium(Nb)</label>
                <div class="col-sm-1">
                <input type="number" class="form-control boxsize mt-1" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" id="nbta" name="_nbta" value="{{elm13}}" title="min: 0&#013;<br>max: 0.002" min="0" max="0.002" step=0.0001 required>
                </div>
                <label for="temp" class="col-sm-2 col-form-label ">Temperature(&#8451)</label>
                <div class="col-sm-1">
                    <input type="number" class="form-control boxsize" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" id="temp" name="_temp" value="{{elm14}}" title="min: 0&#013;<br>max: 650" min="0" max="650" required>
                </div>
                {% if error %}
                <div class="col-sm-3"><p><strong>Error:</strong><span style="color:red;"> {{ error }}</span></div>
                {% endif %}
            </div>
        </div>
    </form>
    <script>
        function clearForm(form) {
            var $f = $(form);
            var $f = $f.find(':input').not(':button, :submit, :reset, :hidden');
            $f.val('').attr('value','').removeAttr('checked').removeAttr('selected');
        }
    </script>
</div>

<script>
    
    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
    var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
    return new bootstrap.Popover(popoverTriggerEl)
    })

    var popover = new bootstrap.Popover(document.querySelector('.popover-dismiss'), {
  trigger: 'focus'
})
</script>

<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
})
</script>
<!--
<form class="form-inline" role="form">
    <label class="control-label" for="inputSuccess4" style="padding-right: 50px;">NAME</label>
    <div class="form-group has-success has-feedback">
      <input type="text" class="form-control" id="inputSuccess4" style="width: 50px;">
      <span class="glyphicon glyphicon-user form-control-feedback" style="padding-left: 10px;"><i class="bi bi-info-circle"></i></span>
    </div>
  </form>
-->

{% endblock %}

web_app/web_app/templates/log.html
{% extends "base.html" %}
{% block content %}


<div class="container fixeddiv">
    <div class="row mb-3">
        <div class="col-sm-3">
            <h4 style="font-family: 'Noto Serif', serif;">Previous Compositions</h4>
        </div>
        <label class="col-sm-8 col-form-label"></label>
        <div class="col-sm-1">
            <button type="button" class="form-control btn btn-danger btn-sm logbuttonsize" data-bs-toggle="modal" data-bs-target="#clearModal" value='Clear' name='Clear'>Clear</button>       
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade modalbox" id="clearModal" tabindex="-1" aria-labelledby="clearModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="clearModalLabel">Confirm</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to clear the logs?</p>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <form action="{{url_for('logs.log')}}" method="POST">
                <button type="submit" class="btn btn-primary" name="Continue" value="Continue">Continue</button>
            </form>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<br>
<div>
    <table class="table table-striped table-hover css-serial" id="alloys">
        <thead>
          <tr class="table-headers">
            <th scope="col">ID</th>
            <th scope="col">Carbon</th>
            <th scope="col">Silicon</th>
            <th scope="col">Manganese</th>
            <th scope="col">Phosphorus</th>
            <th scope="col">Sulphur</th>
            <th scope="col">Nickel</th>
            <th scope="col">Chromium</th>
            <th scope="col">Molybdenum</th>
            <th scope="col">Copper</th>
            <th scope="col">Vanadium</th>
            <th scope="col">Aluminium</th>
            <th scope="col">Nitrogen</th>
            <th scope="col">Niobium</th>
            <th scope="col">Temperature (&#8451)</th>
            <th class="table-primary" table-striped scope="col">Tensile Strength (MPa)</th>
            <th class="table-primary" table-striped scope="col">Yield Strength (MPa)</th>
            <th class="table-primary" table-striped scope="col">Elongation (%)</th>
            <th class="table-primary" table-striped scope="col">Reduction In Area (%)</th>
          </tr>
        </thead>
        <tbody>
            {% for elm in alloys_ %}
                <tr>
                    <td>{{''}}</td>
                    <td>{{elm.c}}</td>
                    <td>{{elm.si}}</td>
                    <td>{{elm.mn}}</td>
                    <td>{{elm.p}}</td>
                    <td>{{elm.s}}</td>
                    <td>{{elm.ni}}</td>
                    <td>{{elm.cr}}</td>
                    <td>{{elm.mo}}</td>
                    <td>{{elm.cu}}</td>
                    <td>{{elm.v}}</td>
                    <td>{{elm.al}}</td>
                    <td>{{elm.n}}</td>
                    <td>{{elm.nt}}</td>
                    <td>{{elm.temp}}</td>
                    <td class="table-primary">{{elm.tensile}}</td>
                    <td class="table-primary">{{elm.yield_}}</td>
                    <td class="table-primary">{{elm.elongation}}</td>
                    <td class="table-primary">{{elm.reduction}}</td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
</div>




{% endblock %}

web_app/web_app/templates/temp_page.html
{% extends "base.html" %}
{%block content%}

<h6>The button is fuckin pressed</h6>
<h6>And the fucking number is </h6><h1>{{num}}</h1>


{%endblock%}